<?php

/*
 |--------------------------------------------------------------------------
 | DO NOT EDIT THIS FILE DIRECTLY.
 |--------------------------------------------------------------------------
 | This file reads from your .env configuration file and should not
 | be modified directly.
*/

// This is used by the mysql dump options in spatie backup
$dump_options = [
    'dump_binary_path' => env('DB_DUMP_PATH', '/usr/local/bin'),  // only the path, so without 'mysqldump'
    'timeout' => 60 * 5, // 5 minute timeout
    // 'exclude_tables' => ['table1', 'table2'],
    // 'add_extra_option' => '--optionname=optionvalue',
];

// Default to false (preserves original behavior for non-RDS installs).
// Set DB_DUMP_SINGLE_TRANSACTION=true in .env for RDS or other environments
// that require --single-transaction (e.g. no LOCK TABLES privilege).
$dump_options['use_single_transaction'] = (env('DB_DUMP_SINGLE_TRANSACTION', 'false') === 'true');

$db_config_path = env('HSBIT_DB_CONFIG_FILE', storage_path('app/secrets/database.php'));

if (is_string($db_config_path) && ($db_config_path !== '') && ! str_starts_with($db_config_path, '/') && preg_match('#^[A-Za-z]:[\\/]#', $db_config_path) !== 1) {
    $db_config_path = base_path($db_config_path);
}

$db_secret_values = [];

if (is_string($db_config_path) && ($db_config_path !== '') && is_readable($db_config_path)) {
    $loaded_db_secret_values = require $db_config_path;

    if (is_array($loaded_db_secret_values)) {
        $db_secret_values = $loaded_db_secret_values;
    }
}

$db_config_value = static function (string $key, $default = null) use ($db_secret_values) {
    return array_key_exists($key, $db_secret_values) ? $db_secret_values[$key] : env($key, $default);
};

// For modern versions of mysqldump, use --ssl-mode=DISABLED
if (env('DB_DUMP_SKIP_SSL') == 'true') {
    // Correctly add the option as a string to the 'add_extra_option' key.
    $dump_options['add_extra_option'] = '--ssl-mode=DISABLED';
}

return [

    /*
    |--------------------------------------------------------------------------
    | PDO Fetch Style
    |--------------------------------------------------------------------------
    |
    | By default, database results will be returned as instances of the PHP
    | stdClass object; however, you may desire to retrieve records in an
    | array format for simplicity. Here you can tweak the fetch style.
    |
    */

    'fetch' => PDO::FETCH_CLASS,

    'hsbit_config_file' => $db_config_path,

    /*
    |--------------------------------------------------------------------------
    | Default Database Connection Name
    |--------------------------------------------------------------------------
    |
    | Here you may specify which of the database connections below you wish
    | to use as your default connection for all database work. Of course
    | you may use many connections at once using the Database library.
    |
    */

    'default' => $db_config_value('DB_CONNECTION', 'mysql'),

    /*
    |--------------------------------------------------------------------------
    | Database Connections
    |--------------------------------------------------------------------------
    |
    | Here are each of the database connections setup for your application.
    | Of course, examples of configuring each database platform that is
    | supported by Laravel is shown below to make development simple.
    |
    |
    | All database work in Laravel is done through the PHP PDO facilities
    | so make sure you have the driver for your particular database of
    | choice installed on your machine before you begin development.
    |
    */

    'connections' => [

        'sqlite' => [
            'driver' => 'sqlite',
            'database' => database_path('database.sqlite'),
            'prefix' => '',
        ],

        'sqlite_testing' => [
            'driver' => 'sqlite',
            'database' => ':memory:',
            'prefix' => '',
        ],

        'mysql' => [
            'driver' => 'mysql',
            'host' => $db_config_value('DB_HOST', 'localhost'),
            'port' => (int) $db_config_value('DB_PORT', 3306),
            'database' => $db_config_value('DB_DATABASE', 'hsb_it'),
            'username' => $db_config_value('DB_USERNAME', 'forge'),
            'password' => $db_config_value('DB_PASSWORD', ''),
            'charset' => env('DB_CHARSET', 'utf8mb4'),
            'collation' => env('DB_COLLATION', 'utf8mb4_unicode_ci'),
            'prefix' => env('DB_PREFIX', null),
            'strict' => false,
            'engine' => 'InnoDB',
            'unix_socket' => $db_config_value('DB_SOCKET', ''),
            'dump' => $dump_options,
            'dump_command_timeout' => 60 * 5, // 5 minute timeout
            'dump_using_single_transaction' => true, // perform dump using a single transaction
            'options' => (env('DB_SSL')) ? ((env('DB_SSL_IS_PAAS')) ? [
                PDO::MYSQL_ATTR_SSL_CA => env('DB_SSL_CA_PATH'),   // /path/to/ca.pem
                PDO::MYSQL_ATTR_SSL_VERIFY_SERVER_CERT => env('DB_SSL_VERIFY_SERVER', false), // true/false
            ] : [
                PDO::MYSQL_ATTR_SSL_KEY => env('DB_SSL_KEY_PATH'),  // /path/to/key.pem
                PDO::MYSQL_ATTR_SSL_CERT => env('DB_SSL_CERT_PATH'), // /path/to/cert.pem
                PDO::MYSQL_ATTR_SSL_CA => env('DB_SSL_CA_PATH'),   // /path/to/ca.pem
                PDO::MYSQL_ATTR_SSL_CIPHER => env('DB_SSL_CIPHER'),
                PDO::MYSQL_ATTR_SSL_VERIFY_SERVER_CERT => env('DB_SSL_VERIFY_SERVER', false), // true/false
            ]) : [],
        ],

        'pgsql' => [
            'driver' => 'pgsql',
            'host' => $db_config_value('DB_HOST', 'localhost'),
            'port' => $db_config_value('DB_PORT', '5432'),
            'database' => $db_config_value('DB_DATABASE', 'hsb_it'),
            'username' => $db_config_value('DB_USERNAME', 'forge'),
            'password' => $db_config_value('DB_PASSWORD', ''),
            'charset' => 'utf8',
            'prefix' => '',
            'schema' => 'public',
            // 'require' when connecting to Cloud SQL for PostgreSQL over its public IP;
            // leave as 'prefer' (or unset) when going through the Cloud SQL Auth Proxy on localhost.
            'sslmode' => $db_config_value('DB_SSLMODE', 'prefer'),
        ],

        'sqlsrv' => [
            'driver' => 'sqlsrv',
            'host' => $db_config_value('DB_HOST', 'localhost'),
            'database' => $db_config_value('DB_DATABASE', 'hsb_it'),
            'username' => $db_config_value('DB_USERNAME', 'forge'),
            'password' => $db_config_value('DB_PASSWORD', ''),
            'charset' => 'utf8',
            'prefix' => '',
        ],

    ],

    /*
    |--------------------------------------------------------------------------
    | Migration Repository Table
    |--------------------------------------------------------------------------
    |
    | This table keeps track of all the migrations that have already run for
    | your application. Using this information, we can determine which of
    | the migrations on disk haven't actually been run in the database.
    |
    */

    'migrations' => 'migrations',

    /*
    |--------------------------------------------------------------------------
    | Redis Databases
    |--------------------------------------------------------------------------
    |
    | Redis is an open source, fast, and advanced key-value store that also
    | provides a richer set of commands than a typical key-value systems
    | such as APC or Memcached. Laravel makes it easy to dig right in.
    |
    */

    'redis' => [

        'cluster' => false,

        'default' => [
            'host' => env('REDIS_HOST', 'localhost'),
            'password' => env('REDIS_PASSWORD', null),
            'port' => env('REDIS_PORT', 6379),
            'database' => env('REDIS_DATABASE', 0),
        ],

    ],

];
